name: Format

on:
  push:
    branches:
      - '**'  # Any branch

jobs:
  format:
    runs-on: ubuntu-latest
    # Add permissions to allow commits
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: '--config ./.prettierrc --ignore-path .gitignore -w "packages/**/*.{js,ts,json,css,tsx,jsx,md}" "playgrounds/**/*.{js,ts,json,css,tsx,jsx,md}"'
          commit_message: "style: auto-format with action"
